server:
  port: 8082
spring:
  application:
    name: store
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  jmx:
    enabled: false

  datasource:
    url: jdbc:sqlserver://localhost;databaseName=payment_challenge
    username: SA
    password: 'p@ssW0rd'
    platform: mssql

