server:
  port: 8080
spring:
  application:
    name: store
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  jmx:
    enabled: false

  datasource:
    url: jdbc:sqlserver://localhost;databaseName=store_challenge
    username: SA
    password: 'p@ssw0rd'
    platform: mssql

