server:
  port: 8081
spring:
  application:
    name: store
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

  jmx:
    enabled: false

  datasource:
    url: jdbc:sqlserver://localhost;databaseName=order_challenge
    username: SA
    password: 'p@ssW0rd'
    platform: mssql

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      exchange: "payment"
      mandatory: true
